import nodemailer from 'nodemailer';

const emailServerUrl = process.env.EMAIL_SERVER_URL;
const emailServerUser = process.env.EMAIL_SERVER_USER;
const emailServerPass = process.env.EMAIL_SERVER_PASS;

const transporter = nodemailer.createTransport({
  host: emailServerUrl,
  port: 465,
  secure: true,
  auth: {
    user: emailServerUser,
    pass: emailServerPass,
  },
});

transporter.verify((error: any) => {
  if (error) {
    // eslint-disable-next-line no-console
    console.error(error);
  } else {
    console.info('Email server is ready to take our messages');
  }
});

export interface EmailTo {
  email: string;
  firstName: string;
  lastName: string;
}

export default async function sendMail(
  to: EmailTo,
  subject: string,
  body: string
) {
  return transporter.sendMail({
    from: {
      name: 'Railway Express',
      address: emailServerUser || '',
    },
    to: to.email, // list of receivers
    subject: `Railway Express - ${subject}`,
    html: `<p>Hello ${to.firstName} ${to.lastName},</p>
    ${body}
    <p>Cheers,<br/>
    Railway Express Team.</p>
    <br/>
    <br/>
    <small>This email is automatically generated by Railway Express. Please do not reply to this email.</small>
    `,
  });
}
